name: Build Windows

on: push

env:
  QT_VERSION: "6.5.0"
  BUILD_TYPE: Release
  COMPILER: msvc
  BUILD_GEN: "Ninja"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        tools: 'tools_cmake tools_ninja'
        cache: 'true'

    - name: Build
      run: cmake -S . -B build -G "${{ env.BUILD_GEN }}" && cmake --build build --config ${{ env.BUILD_TYPE }}
