name: Build Windows

on: push

env:
  QT_VERSION: "6.5.0"
  BUILD_TYPE: Release
  COMPILER: msvc
  BUILD_GEN: "Ninja"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: >-
          mingw-w64-x86_64-openssl
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        host: "windows"
        target: "desktop"
        arch: "win64_msvc2019_64"
        cache: 'true'

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Build
      run: cmake -S . -B build -G "${{ env.BUILD_GEN }}" && cmake --build build --config ${{ env.BUILD_TYPE }}
